// frontend/src/utils/coursePresets.js
// Hardcoded course presets for local favorites
// Par and stroke index data sourced from 18Birdies / GolfPass scorecards

export const COURSE_PRESETS = [
  {
    name: "Meadow Brook Golf Course",
    city: "Gettysburg", state: "PA",
    par_total: 72, slope_rating: 127, course_rating: 69.6,
    holes: [
      // Pars from GolfPass review; stroke indexes estimated (no public source found)
      { hole_number:  1, par: 4, stroke_index: 7  },
      { hole_number:  2, par: 4, stroke_index: 11 },
      { hole_number:  3, par: 3, stroke_index: 15 },
      { hole_number:  4, par: 5, stroke_index: 3  },
      { hole_number:  5, par: 4, stroke_index: 1  },
      { hole_number:  6, par: 5, stroke_index: 13 },
      { hole_number:  7, par: 4, stroke_index: 17 },
      { hole_number:  8, par: 3, stroke_index: 5  },
      { hole_number:  9, par: 4, stroke_index: 9  },
      { hole_number: 10, par: 4, stroke_index: 8  },
      { hole_number: 11, par: 3, stroke_index: 10 },
      { hole_number: 12, par: 4, stroke_index: 16 },
      { hole_number: 13, par: 5, stroke_index: 4  },
      { hole_number: 14, par: 4, stroke_index: 2  },
      { hole_number: 15, par: 3, stroke_index: 14 },
      { hole_number: 16, par: 4, stroke_index: 18 },
      { hole_number: 17, par: 5, stroke_index: 6  },
      { hole_number: 18, par: 4, stroke_index: 12 },
    ],
    note: "Stroke indexes estimated — verify with local scorecard"
  },
  {
    name: "Quail Valley Golf Club",
    city: "Littlestown", state: "PA",
    par_total: 72, slope_rating: 139, course_rating: 74.2,
    holes: [
      { hole_number:  1, par: 4, stroke_index: 15 },
      { hole_number:  2, par: 3, stroke_index: 11 },
      { hole_number:  3, par: 4, stroke_index: 3  },
      { hole_number:  4, par: 5, stroke_index: 5  },
      { hole_number:  5, par: 4, stroke_index: 1  },
      { hole_number:  6, par: 4, stroke_index: 13 },
      { hole_number:  7, par: 3, stroke_index: 17 },
      { hole_number:  8, par: 4, stroke_index: 7  },
      { hole_number:  9, par: 5, stroke_index: 9  },
      { hole_number: 10, par: 4, stroke_index: 14 },
      { hole_number: 11, par: 4, stroke_index: 4  },
      { hole_number: 12, par: 4, stroke_index: 8  },
      { hole_number: 13, par: 3, stroke_index: 12 },
      { hole_number: 14, par: 4, stroke_index: 18 },
      { hole_number: 15, par: 5, stroke_index: 2  },
      { hole_number: 16, par: 4, stroke_index: 10 },
      { hole_number: 17, par: 3, stroke_index: 16 },
      { hole_number: 18, par: 5, stroke_index: 6  },
    ]
  },
  {
    name: "Flatbush Golf Course",
    city: "Littlestown", state: "PA",
    par_total: 71, slope_rating: 128, course_rating: 72.5,
    holes: [
      { hole_number:  1, par: 5, stroke_index: 11 },
      { hole_number:  2, par: 4, stroke_index: 5  },
      { hole_number:  3, par: 3, stroke_index: 15 },
      { hole_number:  4, par: 4, stroke_index: 1  },
      { hole_number:  5, par: 4, stroke_index: 13 },
      { hole_number:  6, par: 3, stroke_index: 17 },
      { hole_number:  7, par: 5, stroke_index: 3  },
      { hole_number:  8, par: 4, stroke_index: 7  },
      { hole_number:  9, par: 4, stroke_index: 9  },
      { hole_number: 10, par: 4, stroke_index: 10 },
      { hole_number: 11, par: 3, stroke_index: 18 },
      { hole_number: 12, par: 4, stroke_index: 16 },
      { hole_number: 13, par: 4, stroke_index: 12 },
      { hole_number: 14, par: 4, stroke_index: 4  },
      { hole_number: 15, par: 5, stroke_index: 2  },
      { hole_number: 16, par: 4, stroke_index: 6  },
      { hole_number: 17, par: 3, stroke_index: 14 },
      { hole_number: 18, par: 4, stroke_index: 8  },
    ]
  },
  {
    name: "Gettysburg National Golf Club",
    city: "Fairfield", state: "PA",
    par_total: 71, slope_rating: 127, course_rating: 70.8,
    holes: [
      { hole_number:  1, par: 4, stroke_index: 6  },
      { hole_number:  2, par: 4, stroke_index: 10 },
      { hole_number:  3, par: 3, stroke_index: 18 },
      { hole_number:  4, par: 4, stroke_index: 12 },
      { hole_number:  5, par: 4, stroke_index: 8  },
      { hole_number:  6, par: 4, stroke_index: 2  },
      { hole_number:  7, par: 3, stroke_index: 16 },
      { hole_number:  8, par: 5, stroke_index: 4  },
      { hole_number:  9, par: 4, stroke_index: 14 },
      { hole_number: 10, par: 4, stroke_index: 11 },
      { hole_number: 11, par: 4, stroke_index: 5  },
      { hole_number: 12, par: 3, stroke_index: 15 },
      { hole_number: 13, par: 4, stroke_index: 7  },
      { hole_number: 14, par: 5, stroke_index: 9  },
      { hole_number: 15, par: 4, stroke_index: 13 },
      { hole_number: 16, par: 4, stroke_index: 1  },
      { hole_number: 17, par: 3, stroke_index: 17 },
      { hole_number: 18, par: 5, stroke_index: 3  },
    ]
  },
  {
    name: "Clayton Park Golf Course",
    city: "Glen Mills", state: "PA",
    par_total: 60, slope_rating: 102, course_rating: 59.9,
    holes: [
      { hole_number:  1, par: 4, stroke_index: 15 },
      { hole_number:  2, par: 3, stroke_index: 9  },
      { hole_number:  3, par: 3, stroke_index: 3  },
      { hole_number:  4, par: 3, stroke_index: 5  },
      { hole_number:  5, par: 3, stroke_index: 1  },
      { hole_number:  6, par: 3, stroke_index: 7  },
      { hole_number:  7, par: 4, stroke_index: 11 },
      { hole_number:  8, par: 3, stroke_index: 13 },
      { hole_number:  9, par: 4, stroke_index: 17 },
      { hole_number: 10, par: 4, stroke_index: 16 },
      { hole_number: 11, par: 3, stroke_index: 10 },
      { hole_number: 12, par: 3, stroke_index: 4  },
      { hole_number: 13, par: 3, stroke_index: 6  },
      { hole_number: 14, par: 3, stroke_index: 2  },
      { hole_number: 15, par: 3, stroke_index: 8  },
      { hole_number: 16, par: 4, stroke_index: 12 },
      { hole_number: 17, par: 3, stroke_index: 14 },
      { hole_number: 18, par: 4, stroke_index: 18 },
    ]
  },
];
