// frontend/src/utils/coursePresets.js
// Hardcoded course presets for local favorites
// Par, stroke index, and tee data sourced from 18Birdies / GolfPass scorecards

export const COURSE_PRESETS = [
  {
    name: "Meadow Brook Golf Course",
    city: "Gettysburg", state: "PA",
    par_total: 72, slope_rating: 127, course_rating: 69.6,
    tees: [
      { tee_name: "Blue",  slope_rating: 127, course_rating: 69.6, par_total: 72 },
      { tee_name: "White", slope_rating: 126, course_rating: 68.3, par_total: 72 },
      { tee_name: "Gold",  slope_rating: 113, course_rating: 65.1, par_total: 72 },
      { tee_name: "Red",   slope_rating: 115, course_rating: 68.3, par_total: 72 },
    ],
    holes: [
      { hole_number:  1, par: 4, stroke_index: 7  },
      { hole_number:  2, par: 4, stroke_index: 11 },
      { hole_number:  3, par: 3, stroke_index: 15 },
      { hole_number:  4, par: 5, stroke_index: 3  },
      { hole_number:  5, par: 4, stroke_index: 1  },
      { hole_number:  6, par: 5, stroke_index: 13 },
      { hole_number:  7, par: 4, stroke_index: 17 },
      { hole_number:  8, par: 3, stroke_index: 5  },
      { hole_number:  9, par: 4, stroke_index: 9  },
      { hole_number: 10, par: 4, stroke_index: 8  },
      { hole_number: 11, par: 3, stroke_index: 10 },
      { hole_number: 12, par: 4, stroke_index: 16 },
      { hole_number: 13, par: 5, stroke_index: 4  },
      { hole_number: 14, par: 4, stroke_index: 2  },
      { hole_number: 15, par: 3, stroke_index: 14 },
      { hole_number: 16, par: 4, stroke_index: 18 },
      { hole_number: 17, par: 5, stroke_index: 6  },
      { hole_number: 18, par: 4, stroke_index: 12 },
    ],
    note: "Stroke indexes estimated — verify with local scorecard"
  },
  {
    name: "Quail Valley Golf Club",
    city: "Littlestown", state: "PA",
    par_total: 72, slope_rating: 139, course_rating: 74.2,
    tees: [
      { tee_name: "Maroon", slope_rating: 139, course_rating: 74.2, par_total: 72 },
      { tee_name: "Black",  slope_rating: 135, course_rating: 72.1, par_total: 72 },
      { tee_name: "White",  slope_rating: 130, course_rating: 70.5, par_total: 72 },
      { tee_name: "Gold",   slope_rating: 125, course_rating: 68.0, par_total: 72 },
      { tee_name: "Green",  slope_rating: 112, course_rating: 64.8, par_total: 72 },
    ],
    holes: [
      { hole_number:  1, par: 4, stroke_index: 15 },
      { hole_number:  2, par: 3, stroke_index: 11 },
      { hole_number:  3, par: 4, stroke_index: 3  },
      { hole_number:  4, par: 5, stroke_index: 5  },
      { hole_number:  5, par: 4, stroke_index: 1  },
      { hole_number:  6, par: 4, stroke_index: 13 },
      { hole_number:  7, par: 3, stroke_index: 17 },
      { hole_number:  8, par: 4, stroke_index: 7  },
      { hole_number:  9, par: 5, stroke_index: 9  },
      { hole_number: 10, par: 4, stroke_index: 14 },
      { hole_number: 11, par: 4, stroke_index: 4  },
      { hole_number: 12, par: 4, stroke_index: 8  },
      { hole_number: 13, par: 3, stroke_index: 12 },
      { hole_number: 14, par: 4, stroke_index: 18 },
      { hole_number: 15, par: 5, stroke_index: 2  },
      { hole_number: 16, par: 4, stroke_index: 10 },
      { hole_number: 17, par: 3, stroke_index: 16 },
      { hole_number: 18, par: 5, stroke_index: 6  },
    ]
  },
  {
    name: "Flatbush Golf Course",
    city: "Littlestown", state: "PA",
    par_total: 71, slope_rating: 128, course_rating: 72.5,
    tees: [
      { tee_name: "Blue",  slope_rating: 128, course_rating: 72.5, par_total: 71 },
      { tee_name: "White", slope_rating: 121, course_rating: 69.7, par_total: 71 },
      { tee_name: "Gold",  slope_rating: 112, course_rating: 66.7, par_total: 71 },
      { tee_name: "Red",   slope_rating: 118, course_rating: 69.0, par_total: 71 },
    ],
    holes: [
      { hole_number:  1, par: 5, stroke_index: 11 },
      { hole_number:  2, par: 4, stroke_index: 5  },
      { hole_number:  3, par: 3, stroke_index: 15 },
      { hole_number:  4, par: 4, stroke_index: 1  },
      { hole_number:  5, par: 4, stroke_index: 13 },
      { hole_number:  6, par: 3, stroke_index: 17 },
      { hole_number:  7, par: 5, stroke_index: 3  },
      { hole_number:  8, par: 4, stroke_index: 7  },
      { hole_number:  9, par: 4, stroke_index: 9  },
      { hole_number: 10, par: 4, stroke_index: 10 },
      { hole_number: 11, par: 3, stroke_index: 18 },
      { hole_number: 12, par: 4, stroke_index: 16 },
      { hole_number: 13, par: 4, stroke_index: 12 },
      { hole_number: 14, par: 4, stroke_index: 4  },
      { hole_number: 15, par: 5, stroke_index: 2  },
      { hole_number: 16, par: 4, stroke_index: 6  },
      { hole_number: 17, par: 3, stroke_index: 14 },
      { hole_number: 18, par: 4, stroke_index: 8  },
    ]
  },
  {
    name: "Gettysburg National Golf Club",
    city: "Fairfield", state: "PA",
    par_total: 71, slope_rating: 127, course_rating: 70.8,
    tees: [
      { tee_name: "Gray",  slope_rating: 127, course_rating: 70.8, par_total: 71 },
      { tee_name: "Blue",  slope_rating: 123, course_rating: 69.3, par_total: 71 },
      { tee_name: "White", slope_rating: 117, course_rating: 66.6, par_total: 71 },
      { tee_name: "Red",   slope_rating: 115, course_rating: 67.4, par_total: 71 },
    ],
    holes: [
      { hole_number:  1, par: 4, stroke_index: 6  },
      { hole_number:  2, par: 4, stroke_index: 10 },
      { hole_number:  3, par: 3, stroke_index: 18 },
      { hole_number:  4, par: 4, stroke_index: 12 },
      { hole_number:  5, par: 4, stroke_index: 8  },
      { hole_number:  6, par: 4, stroke_index: 2  },
      { hole_number:  7, par: 3, stroke_index: 16 },
      { hole_number:  8, par: 5, stroke_index: 4  },
      { hole_number:  9, par: 4, stroke_index: 14 },
      { hole_number: 10, par: 4, stroke_index: 11 },
      { hole_number: 11, par: 4, stroke_index: 5  },
      { hole_number: 12, par: 3, stroke_index: 15 },
      { hole_number: 13, par: 4, stroke_index: 7  },
      { hole_number: 14, par: 5, stroke_index: 9  },
      { hole_number: 15, par: 4, stroke_index: 13 },
      { hole_number: 16, par: 4, stroke_index: 1  },
      { hole_number: 17, par: 3, stroke_index: 17 },
      { hole_number: 18, par: 5, stroke_index: 3  },
    ]
  },
  {
    name: "Clayton Park Golf Course",
    city: "Glen Mills", state: "PA",
    par_total: 30, slope_rating: 102, course_rating: 59.9,
    tees: [
      { tee_name: "White", slope_rating: 102, course_rating: 59.9, par_total: 30 },
    ],
    holes: [
      { hole_number: 1, par: 4, stroke_index: 15 },
      { hole_number: 2, par: 3, stroke_index: 9  },
      { hole_number: 3, par: 3, stroke_index: 3  },
      { hole_number: 4, par: 3, stroke_index: 5  },
      { hole_number: 5, par: 3, stroke_index: 1  },
      { hole_number: 6, par: 3, stroke_index: 7  },
      { hole_number: 7, par: 4, stroke_index: 11 },
      { hole_number: 8, par: 3, stroke_index: 13 },
      { hole_number: 9, par: 4, stroke_index: 17 },
    ]
  },

  {
    name: "Links at Gettysburg",
    city: "Gettysburg", state: "PA",
    par_total: 72, slope_rating: 136, course_rating: 70.5,
    tees: [
      { tee_name: "White", slope_rating: 136, course_rating: 70.5, par_total: 72 },
    ],
    holes: [
      { hole_number:  1, par: 4, stroke_index: 5  },
      { hole_number:  2, par: 4, stroke_index: 3  },
      { hole_number:  3, par: 3, stroke_index: 9  },
      { hole_number:  4, par: 5, stroke_index: 17 },
      { hole_number:  5, par: 4, stroke_index: 11 },
      { hole_number:  6, par: 3, stroke_index: 15 },
      { hole_number:  7, par: 5, stroke_index: 1  },
      { hole_number:  8, par: 4, stroke_index: 13 },
      { hole_number:  9, par: 4, stroke_index: 7  },
      { hole_number: 10, par: 4, stroke_index: 10 },
      { hole_number: 11, par: 4, stroke_index: 16 },
      { hole_number: 12, par: 3, stroke_index: 12 },
      { hole_number: 13, par: 4, stroke_index: 2  },
      { hole_number: 14, par: 5, stroke_index: 6  },
      { hole_number: 15, par: 3, stroke_index: 14 },
      { hole_number: 16, par: 4, stroke_index: 4  },
      { hole_number: 17, par: 4, stroke_index: 8  },
      { hole_number: 18, par: 5, stroke_index: 18 },
    ]
  },
  {
    name: "Caledonia Golf Club",
    city: "Fayetteville", state: "PA",
    par_total: 68, slope_rating: 118, course_rating: 67.1,
    tees: [
      { tee_name: "White", slope_rating: 118, course_rating: 67.1, par_total: 68 },
    ],
    holes: [
      // Stroke indexes not available — using estimated values
      { hole_number:  1, par: 4, stroke_index: 7  },
      { hole_number:  2, par: 5, stroke_index: 3  },
      { hole_number:  3, par: 3, stroke_index: 15 },
      { hole_number:  4, par: 3, stroke_index: 17 },
      { hole_number:  5, par: 4, stroke_index: 1  },
      { hole_number:  6, par: 3, stroke_index: 13 },
      { hole_number:  7, par: 3, stroke_index: 11 },
      { hole_number:  8, par: 4, stroke_index: 5  },
      { hole_number:  9, par: 3, stroke_index: 9  },
      { hole_number: 10, par: 5, stroke_index: 4  },
      { hole_number: 11, par: 4, stroke_index: 8  },
      { hole_number: 12, par: 4, stroke_index: 6  },
      { hole_number: 13, par: 3, stroke_index: 18 },
      { hole_number: 14, par: 5, stroke_index: 2  },
      { hole_number: 15, par: 3, stroke_index: 16 },
      { hole_number: 16, par: 4, stroke_index: 10 },
      { hole_number: 17, par: 4, stroke_index: 12 },
      { hole_number: 18, par: 4, stroke_index: 14 },
    ],
    note: "Stroke indexes estimated — verify with local scorecard"
  },

  {
    name: "Carroll Valley Golf Resort",
    city: "Fairfield", state: "PA",
    par_total: 71, slope_rating: 128, course_rating: 72.3,
    tees: [
      { tee_name: "Blue",  slope_rating: 128, course_rating: 72.3, par_total: 71 },
      { tee_name: "White", slope_rating: 127, course_rating: 70.7, par_total: 71 },
      { tee_name: "Gold",  slope_rating: 123, course_rating: 66.7, par_total: 71 },
      { tee_name: "Red",   slope_rating: 115, course_rating: 67.2, par_total: 71 },
    ],
    holes: [
      { hole_number:  1, par: 5, stroke_index: 7  },
      { hole_number:  2, par: 4, stroke_index: 5  },
      { hole_number:  3, par: 3, stroke_index: 17 },
      { hole_number:  4, par: 5, stroke_index: 1  },
      { hole_number:  5, par: 3, stroke_index: 15 },
      { hole_number:  6, par: 4, stroke_index: 11 },
      { hole_number:  7, par: 4, stroke_index: 9  },
      { hole_number:  8, par: 3, stroke_index: 13 },
      { hole_number:  9, par: 5, stroke_index: 3  },
      { hole_number: 10, par: 4, stroke_index: 8  },
      { hole_number: 11, par: 3, stroke_index: 12 },
      { hole_number: 12, par: 5, stroke_index: 4  },
      { hole_number: 13, par: 4, stroke_index: 10 },
      { hole_number: 14, par: 4, stroke_index: 6  },
      { hole_number: 15, par: 3, stroke_index: 16 },
      { hole_number: 16, par: 4, stroke_index: 2  },
      { hole_number: 17, par: 5, stroke_index: 14 },
      { hole_number: 18, par: 3, stroke_index: 18 },
    ]
  },
];
